### ISSUE TITLE
fetch!/3 should have default empty list for options

### ISSUE THREAD

**Issue by stevensonmt** [mcrumm/req_aoc#1]
Right now `fetch!/2` only matches the deprecated API. Adding a default empty list to the options arg for `fetch!/3` should fix that.
Current:
`def fetch!(session, {year, day}, options)`
Suggested:
`def fetch!(session, {year, day}, options \\ [])`

**Comment by mcrumm** [comment]
Nice catch! I should just drop the old function signature but I will leave it for now for the folks who did not specify a git ref when installing :)
